docs: regenerate wallet gateway config schema
Signed-off-by: Chien-An Lin <clin@blockdaemon.com>

diff --git a/.github/actions/setup_canton/action.yml b/.github/actions/setup_canton/action.yml
--- a/.github/actions/setup_canton/action.yml
+++ b/.github/actions/setup_canton/action.yml
@@ -18,8 +18,8 @@ runs:
               NETWORK="${{ inputs.network }}"
               INSTANCE="${{ inputs.instance }}"
 
-              if [ "$NETWORK" != "devnet" ] && [ "$NETWORK" != "mainnet" ]; then
-                echo "Invalid network '$NETWORK'. Expected one of: devnet, mainnet" >&2
+              if [ "$NETWORK" != "devnet" ] && [ "$NETWORK" != "testnet" ] && [ "$NETWORK" != "mainnet" ]; then
+                echo "Invalid network '$NETWORK'. Expected one of: devnet, testnet, mainnet" >&2
                 exit 1
               fi
 
